### ISSUE TITLE
Problems with octokit

### ISSUE THREAD

**Issue by GillesC** [cmaujean/dashing-github-stats#15]
Hello

The following error is thrown when running your application:
`LoadError: cannot load such file -- octokit`
I have installed octokit through `sudo gem install octokit`

**Comment by GillesC** [comment]
I have solved this issue by manual adding these gems to the `Gemfile`. This could be maybe added to the documentation.

**Comment by cmaujean** [comment]
The octokit and actionview gems are listed as being needed in README.md.
Thank you for using the plugin, and contributing fixes. Are you running
this in Smashing or in the final Dashing version?
